version: 1.0.0.{build}

environment:
  matrix:
    - VS_VERSION: 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHONPATH: C:\Python38-x64

    - VS_VERSION: 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHONPATH: C:\Python39-x64

platform:
  - x64
  - Win32

#configuration:
#  - Release
#  - Debug

install:
  - set PATH=%PYTHONPATH%;%PYTHONPATH%\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install cookiecutter
  - cd "%APPVEYOR_BUILD_FOLDER%\.."
  - cookiecutter cookiecutter-npp-cpp-plugin --no-input

  - if "%platform%"=="x64" set archi=amd64
  - if "%platform%"=="x64" set build_platform=x64

  - if "%platform%"=="Win32" set archi=x86
  - if "%platform%"=="Win32" set build_platform=Win32

  - call "C:\Program Files (x86)\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build:
  parallel: true
  verbosity: minimal

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\..\MyPlugin"
  - msbuild MyPlugin.sln /m /p:Configuration="Release" /p:Platform="%build_platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild MyPlugin.sln /m /p:Configuration="Debug" /p:Platform="%build_platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
