version: 1.0.0.{build}
image: Visual Studio 2017

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug

install:
  - pip install cookiecutter
  - cd "%APPVEYOR_BUILD_FOLDER%\.."
  - cookiecutter cookiecutter-npp-cpp-plugin --no-input

  - if "%platform%"=="x64" set archi=amd64
  - if "%platform%"=="x64" set build_platform=x64

  - if "%platform%"=="Win32" set archi=x86
  - if "%platform%"=="Win32" set build_platform=Win32

  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build:
  parallel: true
  verbosity: minimal

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\..\MyPlugin"
  - msbuild MyPlugin.sln /p:Configuration="%configuration%" /p:Platform="%build_platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
